### ISSUE TITLE
Support for Multiple Lists?

### ISSUE THREAD

**Issue by shirasp** [kevdliu/hassio-addon-anylist#1]
Hello! I have added/installed both the add on and the custom HACS repository for AnyList, but was curious how to set up the config for multiple lists? Currently my Add-On configuration looks like this:
![image](https://github.com/kevdliu/hassio-addon-anylist/assets/83919602/9acd8186-18bb-46f2-b540-e6cf2c73f134)

but we have many more lists set up than just the one. If I wanted to also include a second list, would that be possible?

**Comment by kevdliu** [comment]
That's a good idea. It's not currently possible but should be pretty easy to add.

**Comment by kevdliu** [comment]
Also just out of curiosity are you using the integration via service calls or intents/voice?

**Comment by kevdliu** [comment]
Updated the addon and integration to support multiple lists.

**Comment by shirasp** [comment]
Thank you! Thats great!
And to answer your question, I think I will be using it with the service calls. I dont have voice set up in my system yet.
