### ISSUE TITLE
500 Response

### ISSUE THREAD

**Issue by kbromer** [kevdliu/hassio-addon-anylist#4]
Thanks so much for pulling this together.  Have everything configured and running, the add-on and integration successfully pull my list of Lists from AnyList as expected.  The issue I have occurs when I attempt to query one of the lists using the get_items service. I can confirm there are items that do exist in the app, however: 

![image](https://github.com/kevdliu/hassio-addon-anylist/assets/926530/03bd383a-e36f-495f-aea8-3ba31e564856)

As you can see, it returns a 500 response from the server. I can successfully pull my list of lists directly from the add-on through the front end by http://<my local ip>/lists

Only thing I can think is perhaps the integration requires the paid AnyList subscription? I'm currently using the free version of their service?  If so, that's understandable, but may be helpful to note in the readme. 

TIA for any insight and for creating the integration

**Comment by kevdliu** [comment]
Hi Kevin, the `list` parameter of the `anylist.get_items` service accepts the actual name of the list (as shown in Anylist), not an entity id. In your case, assuming the name of your list is Costco, the service call would look like this:
```
service: anylist.get_items
data:
  list: Costco
```

Alternatively, you can also use the `todo.get_items` service call provided by Home Assistant which does accept entity id. For example:
```
service: todo.get_items
target:
  entity_id: todo.anylist_costco
```

**Comment by kbromer** [comment]
Thanks for the pointer kevdliu. I still get the same error when using the anylist.get_items service and any variation of an existing Anylist list name, however your alternate method of using the built-in todo services worked great. Appreciate the help!

**Comment by kevdliu** [comment]
Glad to hear that it's working now. Could you post a screenshot of how you were calling the `anylist.get_items` service so I investigate whether there's anything broken with that service call.

**Comment by kbromer** [comment]
Sure thing:

![image](https://github.com/kevdliu/hassio-addon-anylist/assets/926530/bf8c2572-85b7-42fe-b4ae-4b4b5c83c7c2)

I've also tried it with single quotes, double quotes, prepended with anylist_, preprended with anylist, etc. and confirmed it still returns the 500 error.

**Comment by kevdliu** [comment]
Thanks for the screenshot. It's weird that `todo.get_items` while `anylist.get_items` is not since they both use the addon as the backend. If you pull the list of lists from the /list endpoint, is the list name spelled exactly as "Costco" with the capital C?

**Comment by kbromer** [comment]
Ah... figured it out.  For whatever reason it has a trailing space that isn't visible in the UI - the endpoint made it clearer: 

<img width="319" alt="image" src="https://github.com/kevdliu/hassio-addon-anylist/assets/926530/ac6bf0bc-895f-48dc-ab39-9e758ac601c6">

Retrieving it with single quotes including a trailing whitespace does the trick - 

One probably unrelated note: although the integration works well (adding/deleting/viewing), the Add-On shows as not running in the UI. Not sure if I put into an odd state or there's something else at issue: 

![image](https://github.com/kevdliu/hassio-addon-anylist/assets/926530/cf571c5b-f45b-429c-89ab-578ab2d30237)

**Comment by kevdliu** [comment]
Glad you were able to figure it out! I can probably make the list name matching a little more lenient in a future update. Re: addon, that might be a bug with the webpage. Does it fix itself if you refresh?

**Comment by kbromer** [comment]
Refresh didn't work, but the 2024.1.x update did, so I'll chalk it up to instance-specific gremlins. 🤷‍♂️
