### ISSUE TITLE
Unexpected mimetype when retrieving changelog

### ISSUE THREAD

**Issue by stormshaker** [kevdliu/hassio-addon-anylist#7]
This error is being thrown by Home Assistant Supervisor today:

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:612
integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 4:23:35 AM (198 occurrences)
Last logged: 12:32:24 PM

Client error on /addons/180b202a_anylist/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/180b202a_anylist/changelog')

**Comment by Daneish** [comment]
I also got that error with AnyList, but I also had a few other add ons give the same error; so perhaps it was an issue with GitHub.

Other add-on errors:
>Client error on /addons/77f1785d_matter_server/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/77f1785d_matter_server/changelog')
Client error on /addons/a0d7b954_portainer/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/a0d7b954_portainer/changelog')
Client error on /addons/09e60fb6_scrypted/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/09e60fb6_scrypted/changelog')

**Comment by Daneish** [comment]
Whoops not a GitHub issue, but according to https://github.com/home-assistant/core/issues/116470 it is affecting many other add-ons and reportedly started occurring after a Supervisor update 2024.04.4. [This comment](https://github.com/home-assistant/core/issues/116470#issuecomment-2088569489) reports creating CHANGELOG.md file in the repository resolves the issue.

Having said that, I have other add-ons that aren’t giving errors and they don’t have a changelog file, so I’m not clear on what the underlying cause is.

**Comment by kevdliu** [comment]
Huh interesting I didn't know having a change log is a requirement now. For testing purposes, I created an empty changelog file in the repo. Hopefully that'll at least get rid of the rror.

**Comment by Daneish** [comment]
Thank you! I don’t think it is a documented requirement. As per https://github.com/home-assistant/supervisor/pull/5064 it seems like it was an accidental change. But I can confirm after a reboot, I’m no longer getting the error with the AnyList add-on.

**Comment by kevdliu** [comment]
Ah I see. Thanks for testing the change!
